Напишите функцию get_chess(a), которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a), заполненный 0 и 1 в шахматном порядке. В левом верхнем углу всегда должен быть ноль.

Примечание. воспользуйтесь функцией np.zeros, а затем с помощью срезов без циклов задайте необходимым элементам значение 1.

В Python для получения каждого второго элемента используется срез [::2]. Подумайте, как грамотно применить этот принцип к двумерному массиву.

In [ ]:
import numpy as np
def get_chess(a):
    zeros = np.zeros((a, a))
    zeros[1::2,::2]=1
    zeros[::2,1::2]=1
    
    return zeros
    

print(get_chess(2))

Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста. 
Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. 
Однако вы не хотите хранить в памяти новую версию плейлиста, а просто хотите сохранять тот seed, с которым он был сгенерирован.

Для этого напишите функцию shuffle_seed(array), которая принимает на вход массив из чисел, генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж: перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.

Пример


array = [1, 2, 3, 4, 5]
shuffle_seed(array)
# (array([1, 3, 2, 4, 5]), 2332342819)
shuffle_seed(array)
# (array([4, 5, 2, 3, 1]), 4155165971)

In [ ]:
import numpy as np

def shuffle_seed(array):
    seed_value = np.random.randint(1,2**32 - 1 )
    array_shuffle = np.array(array).copy()
    np.random.seed(seed_value)
    np.random.shuffle(array_shuffle)
    
    return(array_shuffle, seed_value)


#def shuffle_seed(array):
    # Шаг 1: Генерируем случайный seed
    seed = np.random.randint(0, 2**32)  # например, 123456789
    
    # Шаг 2: Создаем копию массива
    array_copy = np.array(array).copy()  # [1, 2, 3, 4, 5]
    
    # Шаг 3: Устанавливаем seed
    np.random.seed(seed)  # "Открываем книгу на странице 123456789"
    
    # Шаг 4: Перемешиваем копию
    np.random.shuffle(array_copy)  # Читаем числа с этой страницы для перемешивания
    
    return (array_copy, seed)

Напишите функцию min_max_dist(*vectors), которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.

Пример


vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

min_max_dist(vec1, vec2, vec3)
# (5.196152422706632, 10.392304845413264)

Объяснение работы:

*vectors - принимает любое количество аргументов

np.array(vectors) - преобразует входные векторы в массив NumPy

Двойной цикл - перебирает все уникальные пары векторов (i, j где i < j)

np.linalg.norm(vectors[i] - vectors[j]) - вычисляет Евклидово расстояние:

vectors[i] - vectors[j] - разность векторов

np.linalg.norm() - вычисляет длину вектора (корень из суммы квадратов)

Обновление min/max - отслеживаем минимальное и максимальное расстояние

Математическая формула расстояния:
Для векторов a = [a₁, a₂, a₃] и b = [b₁, b₂, b₃]:

text
distance = √((a₁-b₁)² + (a₂-b₂)² + (a₃-b₃)²)

In [ ]:
import numpy as np
def min_max_dist(*vectors):
    vectors = np.array(vectors)
    min_dist = float('inf')
    max_dist = 0
    n = len(vectors)
    for i in range(n):
        for j in range(i+1,n):
            dist = np.linalg.norm(vectors[i] - vectors[j])
            if dist < min_dist:
                min_dist = dist
            if dist > max_dist:
                max_dist = dist
                
    return(min_dist,max_dist)

Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую. Гарантируется, что все векторы, которые передаются, одинаковой длины.

Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.

In [ ]:
import numpy as np
def any_normal(*vectors):
    vectors = np.array(vectors)
    n = len(vectors)
    for i in range(n):
        for j in range(i+1,n):
            check = np.dot(i,j)
            if check == 0:
                return True
            else:
                return False

Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно). Это поля для игры в лото.

Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).

Функция возвращает полученный массив.

Пример

get_loto(3)
Результат:

array([[[ 35,  66,  38,  11,  32],
       [ 32,   7,  37,  83,  42],
       [ 89,  37,  19,  51,  89],
       [ 70, 100,  83,   5,  11],
       [ 20,  13,  60,  26,  41]],

      [[ 23,  49,  76,  44,  43],
       [ 59,  63,  99,  92,   2],
       [ 83,   4,  25,  73,  19],
       [ 10,  18,  40,  11,  21],
       [ 58,  45,  73,  93,  61]],

      [[100,  88,  70,  34,  51],
       [  5,  35,  36,  85,  88],
       [ 72,  23,  87,  30,  40],
       [ 29,  21,  51,  73,  81],
       [ 91,  19,  87,  60,  27]]])

In [ ]:
import numpy as np

def get_loto(num):
    """
    Генерирует num полей для игры в лото
    
    Parameters:
    num - количество полей (таблиц 5x5)
    
    Returns:
    Трехмерный массив формы (num, 5, 5) со случайными числами от 1 до 100
    """
    # Генерируем все числа сразу и преобразуем в нужную форму
    return np.random.randint(1, 101, size=(num, 5, 5))

Напишите функцию get_unique_loto(num). Она так же, как и функция в задании 49.9.10, генерирует num полей для игры в лото, однако теперь на каждом поле 5х5 числа не могут повторяться.

Функция также должна возвращать массив формы num x 5 x 5.

Пример

get_unique_loto(3)
Результат:

array([[[26, 91, 73,  7, 16],
       [46, 85, 78, 77, 51],
       [84, 86, 55, 71, 58],
       [17, 61, 50, 30, 97],
       [66, 29, 38, 41, 32]],

      [[49, 32,  3, 21, 85],
       [45,  8, 94, 46, 96],
       [41, 38, 58, 37, 98],
       [66, 77, 54, 80, 26],
       [62, 63, 72,  5, 43]],

      [[55, 60,  6, 80, 97],
       [23, 69, 94,  9, 24],
       [17, 98, 27, 63, 79],
       [84, 74, 51, 39, 54],
       [77, 30, 48, 75, 85]]])


Объяснение ключевых моментов:

np.random.choice(range(1, 101), size=25, replace=False) - выбирает 25 уникальных чисел из диапазона 1-100

replace=False гарантирует, что числа не повторяются

reshape(5, 5) - преобразует линейный массив из 25 чисел в матрицу 5×5

Важно: Числа уникальны только в пределах одного поля, но могут повторяться между разными полями

In [ ]:
def get_unique_loto(num):
    # Генерируем все числа сразу
    all_numbers = np.random.choice(range(1, 101), size=(num, 25), replace=False)
    # Преобразуем в поля 5x5
    return all_numbers.reshape(num, 5, 5)