Векторы в NumPy и арифметика

In [2]:
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [2]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [6]:
vec = np.arange(5)
print(vec)
print(vec * 10)

vec ** 2

[0 1 2 3 4]
[ 0 10 20 30 40]


array([ 0,  1,  4,  9, 16])

In [7]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
 
vec1 > vec2

array([False, False,  True, False])

In [8]:
vec = np.array([14,15,9,26,53,5,89])
vec <= 26

array([ True,  True,  True,  True, False,  True, False])

Продвинутые операции с векторами

In [9]:
#Длина вектора, то есть расстояние между его началом и концом, [в евклидовом пространстве] вычисляется как квадратный корень из суммы квадратов всех его координат
vec = np.array([3, 4])
length = np.sqrt(np.sum(vec ** 2))
print(length)

5.0


In [12]:
#Но можно было поступить проще. В NumPy есть специальный подмодуль linalg, который позволяет производить операции из линейной алгебры.
#Для вычисления длины вектора нам потребуется функция norm:
length = np.linalg.norm(vec)
print(length)

5.0


In [ ]:
#Расстояние между двумя векторами, то есть расстояние между их концами, [в евклидовом пространстве] вычисляется как квадратный корень из суммы квадратов разностей соответствующих координат
# По сути, расстояние между векторами — это длина такого вектора, который является разностью этих векторов. В самом деле, при вычитании двух векторов вычитаются их соответствующие координаты.
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance

In [14]:
#Наконец, скалярным произведением двух векторов называют сумму произведений их соответствующих координат
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.dot(vec1, vec2)
scalar_product

np.float64(250.0)

In [ ]:
#Скалярное произведение также имеет широкое применение в математике и других операциях с векторами. 
# В частности, равенство скалярного произведения нулю означает перпендикулярность рассматриваемых векторов:
x = np.array([25, 0])
y = np.array([0, 10])
np.dot(x, y)
#Здесь были специально заданы векторы, параллельные осям  и  (так как одна из координат в них равна нулю). 
# Они перпендикулярны, как перпендикулярны соответствующие оси, а скалярное произведение действительно равно нулю.

In [3]:
#Базовые статистические функции для векторов
#Функции np.min и np.max позволяют находить максимальное и минимальное значение в векторе. 
# Их можно записывать как в виде np.min(<vector>), так и в виде <vector>.min():
vec = np.array([2,7,18,28,18,1,8,4])
vec.min()
np.max(vec)

np.int64(28)

In [4]:
#Функция mean позволяет посчитать среднее значение. 
# Больше не требуется реализовывать её «руками»!

vec.mean()

np.float64(10.75)

Случайные числа в NumPy
Для генерации псевдослучайных чисел в NumPy существует подмодуль random.



In [5]:
#Самой «базовой» функцией в нём можно считать функцию rand. 
# По умолчанию она генерирует число с плавающей точкой между 0 (включительно) и 1 (не включительно)
import numpy as np
np.random.rand()

0.8725794448468454

In [6]:
np.random.rand() * 100


33.00118931592087

In [7]:
#На самом деле rand умеет генерировать не только отдельные числа — функция принимает в качестве аргументов через запятую целые числа, которые задают форму генерируемого массива. 
#Например, получим массив из пяти случайных чисел:
np.random.rand(5)


array([0.5804548 , 0.76752511, 0.44303299, 0.191362  , 0.23853329])

In [8]:
#Массив из двух случайных строк и трёх столбцов:
np.random.rand(2, 3)

array([[0.06269701, 0.95132999, 0.56792058],
       [0.46153794, 0.45502065, 0.12626888]])

In [9]:
#Функция rand может принимать неограниченное число целых чисел для задания формы массива:
np.random.rand(2, 3, 4, 10, 12, 23)

array([[[[[[0.9782315 , 0.93353205, 0.84312276, ..., 0.15208942,
            0.6568551 , 0.12537065],
           [0.14196697, 0.56939194, 0.02223692, ..., 0.2403617 ,
            0.26629861, 0.64611011],
           [0.78311895, 0.36433526, 0.73144495, ..., 0.8235444 ,
            0.17975958, 0.67509002],
           ...,
           [0.99846589, 0.42222296, 0.03360589, ..., 0.92967264,
            0.06208704, 0.53871396],
           [0.31139131, 0.01226452, 0.55122118, ..., 0.17155025,
            0.08512383, 0.06185767],
           [0.13437251, 0.19112291, 0.76388163, ..., 0.96125162,
            0.9080778 , 0.07577407]],

          [[0.96412723, 0.09548618, 0.24238541, ..., 0.25014152,
            0.97004832, 0.97267449],
           [0.61787617, 0.83524236, 0.71678197, ..., 0.472419  ,
            0.11120356, 0.29702361],
           [0.65563444, 0.12133015, 0.84465235, ..., 0.06241532,
            0.3296783 , 0.28138956],
           ...,
           [0.45941574, 0.58878415, 0.85864609, 

In [10]:
#Обратите внимание, что обычно форму массивов мы задавали в функциях NumPy одним числом или кортежем, а не перечисляли её в виде аргументов через запятую.
#Если передать в rand кортеж, возникнет ошибка:

shape = (3, 4)
np.random.rand(shape)

TypeError: 'tuple' object cannot be interpreted as an integer

In [11]:
#Но в NumPy есть и другая функция, генерирующая массивы случайных чисел от 0 до 1, которая принимает в качестве аргумента именно кортеж без распаковки. 
# Она называется sample:
shape = (2, 3)
np.random.sample(shape)

array([[0.50894151, 0.63523985, 0.79865792],
       [0.44759473, 0.32333437, 0.16988982]])

In [ ]:
#Не всегда требуются числа в диапазоне именно от 0 до 1. 
# На самом деле с помощью специальных формул можно из диапазона от 0 до 1 получить любой другой желаемый диапазон, однако это не требуется делать самостоятельно — 
# в NumPy доступна функция uniform:
uniform(low=0.0, high=1.0, size=None)
#Первые два аргумента — нижняя и верхняя границы диапазона в формате float, третий опциональный аргумент — форма массива (если не задан, возвращается одно число). 
# Форма массива задаётся кортежем или одним числом.

NameError: name 'uniform' is not defined

In [13]:
np.random.uniform()

0.04430335787426498

In [14]:
np.random.uniform(-30, 50)

-12.604907821988213

In [15]:
np.random.uniform(0.5, 0.75, size=5)

array([0.74604567, 0.50670016, 0.56363537, 0.52335055, 0.58482252])

In [16]:
np.random.uniform(-1000, 500, size=(2, 3))

array([[-846.16234215,   96.54034107,  427.43688069],
       [-686.66323261,  211.01039141, -622.53338955]])

In [ ]:
#Генерация int
#Не всегда требуется генерировать числа с плавающей точкой. Иногда бывает удобно получить целые числа int (например, для поля игры в лото). Для генерации целых чисел используется функция random.randint:

In [ ]:
randint(low, high=None, size=None, dtype=int)
#Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.

#Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.
# если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).
#size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.
# dtype позволяет задать конкретный тип данных, который должен быть использован в массиве.

In [17]:
np.random.randint(4, size=(2,3))

array([[1, 2, 0],
       [1, 0, 2]], dtype=int32)

Генерация выборок

In [18]:
#Просто перемешать все числа в массиве позволяет функция random.shuffle.
arr = np.arange(6)
print(arr)

print(np.random.shuffle(arr))

arr

[0 1 2 3 4 5]
None


array([2, 1, 3, 5, 0, 4])

In [19]:
#Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation. 
# Она принимает на вход один аргумент — или массив целиком, или одно число
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
print(playlist)

['Deep Purple' 'The Beatles' 'ACDC' 'Pink Floyd']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [20]:
#Перемешать набор чисел от 0 до n-1 можно с помощью записи np.random.permutation(n), где n — верхняя граница, которая бы использовалась для генерации набора чисел функцией arange.
np.random.permutation(10)

array([6, 8, 3, 4, 7, 0, 2, 9, 1, 5], dtype=int32)

In [ ]:
#Чтобы получить случайный набор объектов из массива, используется функция random.choice:
choice(a, size=None, replace=True)
#a — одномерный массив или число для генерации arange(a);
#size — желаемая форма массива (число для получения одномерного массива, кортеж — для многомерного; если параметр не задан, возвращается один объект);
#replace — параметр, задающий, могут ли элементы повторяться (по умолчанию могут).


In [22]:
dps = ['EDENYA', 'DED', 'MOLNYA', 'RONKYBOY', 'RIPWAR','SHREK']
 
choice = np.random.choice(dps, size=2, replace=False)
print(f"{choice} - ЛАКИ БОЙС")

['RONKYBOY' 'RIPWAR'] - ЛАКИ БОЙС


In [29]:
#Seed генератора псевдослучайных чисел
np.random.seed(23)
np.random.randint(10, size=(3,4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]], dtype=int32)

В simple сохраните случайное число в диапазоне от 0 до 1

Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их в переменную randoms

Получите массив из случайных целых чисел от 1 до 100 (включительно) из 3 строк и 2 столбцов. Сохраните результат в table

В переменную even сохраните четные числа от 2 до 16 (включительно)

Скопируйте even в переменную mix. Перемешайте числа в mix так, чтобы массив изменился

Получите из even 3 числа без повторений. Сохраните их в переменную select

Получите переменную triplet, которая должна содержать перемешанные значения из массива select (сам select измениться не должен)