NumPy


In [16]:
import numpy as np
a = np.int64(121)
print(a)
np.iinfo(a)
b = np.uint32(124)
print(b)
# 124
print(type(b))
# <class 'numpy.uint8'> 
np.iinfo(b)
# iinfo(min=0, max=18446744073709551615, dtype=uint64)

121
124
<class 'numpy.uint32'>


iinfo(min=0, max=4294967295, dtype=uint32)

In [17]:
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


In [9]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [10]:
print(np.sctypeDict)

{'bool': <class 'numpy.bool'>, 'float16': <class 'numpy.float16'>, 'float32': <class 'numpy.float32'>, 'float64': <class 'numpy.float64'>, 'longdouble': <class 'numpy.longdouble'>, 'complex64': <class 'numpy.complex64'>, 'complex128': <class 'numpy.complex128'>, 'clongdouble': <class 'numpy.clongdouble'>, 'bytes_': <class 'numpy.bytes_'>, 'str_': <class 'numpy.str_'>, 'void': <class 'numpy.void'>, 'object_': <class 'numpy.object_'>, 'datetime64': <class 'numpy.datetime64'>, 'timedelta64': <class 'numpy.timedelta64'>, 'int8': <class 'numpy.int8'>, 'byte': <class 'numpy.int8'>, 'uint8': <class 'numpy.uint8'>, 'ubyte': <class 'numpy.uint8'>, 'int16': <class 'numpy.int16'>, 'short': <class 'numpy.int16'>, 'uint16': <class 'numpy.uint16'>, 'ushort': <class 'numpy.uint16'>, 'intc': <class 'numpy.intc'>, 'uintc': <class 'numpy.uintc'>, 'int32': <class 'numpy.int32'>, 'long': <class 'numpy.int32'>, 'uint32': <class 'numpy.uint32'>, 'ulong': <class 'numpy.uint32'>, 'int64': <class 'numpy.int64'

Массивы NumPy

In [ ]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr
d_arr = np.array([[1,2,3,4],[4,7,3,7]])
d_arr


dtype('int64')

In [23]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr.dtype

dtype('int8')

In [25]:
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [27]:
arr = np.float64(arr)
arr

array([  1.,   5., 125.,   9.,  10.])

In [28]:
arr = np.array([1,5,2,9,10], dtype = np.int8)
nd_arr = np.array([[12,45,78],[34,56,13],[12,98,76],[43,23,78]], dtype = np.int16)

In [ ]:
arr.ndim
#размерность

1

In [ ]:
nd_arr.ndim
#размерность

2

In [31]:
arr.size
#число элем в массиве

5

In [32]:
nd_arr.size
#число элем в массиве

12

In [33]:
arr.shape
#форма массива, возврат в форме кортежа

(5,)

In [34]:
nd_arr.shape
#форма массива, возврат в форме кортежа

(4, 3)

In [35]:
arr.itemsize
#сколько байт в памяти под каждый элемент

1

In [36]:
nd_arr.itemsize
#сколько байт в памяти под каждый элемент

2

In [37]:
#создание пустого массива из нулей. тк нельзя создать просто пустой массив
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [38]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
zeros_3d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [39]:
np.arange(5)
#np.arange - это функция из библиотеки NumPy, которая создает массивы с равномерно распределенными значениями в заданном диапазоне.
#Синтаксис:np.arange([start,] stop[, step,], dtype=None)
#start (необязательный) - начало диапазона (по умолчанию 0)
#stop - конец диапазона (не включается)
#step (необязательный) - шаг (по умолчанию 1)

#dtype (необязательный) - тип данных массива
#Результат - массив NumPy, а не список Python
#print(np.arange(5))  # [0 1 2 3 4]
#print(np.arange(2, 6))  # [2 3 4 5]
#print(np.arange(1, 10, 2))  # [1 3 5 7 9]

array([0, 1, 2, 3, 4])

In [40]:
np.linspace(1, 2, 10) 
#np.linspace(start, stop, num) - задается количество точек

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [42]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(step)

0.45


Модуль 2. Погружение в типы данных

In [43]:
import numpy as np
arr = np.arange(8)
arr
# array([0, 1, 2, 3, 4, 5, 6, 7])

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Поменять форму массива arr можно с помощью присвоения атрибуту shape кортежа с желаемой формой: первое число задало число строк, а второе — число столбцов.

arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
#Чтобы оставить исходный массив без изменений и дополнительно получить новый массив новой формы, нужно использовать функцию reshape. 
# Она также принимает в качестве аргумента кортеж из чисел для формы, но возвращает новый массив, а не изменяет исходный:
arr = np.arange(8)
arr_new = arr.reshape((2,4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
#У функции reshape есть дополнительный именованный аргумент order. Он задаёт принцип, по которому элементы заполняют массив новой формы. 
# Если order='C' (по умолчанию), массив заполняется по строкам, как в примере выше. Если order='F', массив заполняется числами по столбцам:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [48]:
#Ещё одной часто используемой операцией с формой массива (особенно двумерного) является транспонирование. Эта операция меняет строки и столбцы массива местами. 
# В NumPy эту операцию совершает функция transpose.
#Будем работать с двумерным массивом:
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [49]:
#Транспонируем его:
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

Индексы и срезы в массивах

In [50]:
#В определении массива указано, что он позволяет быстро получать элементы по индексу. Как же это происходит?
#Создадим массив из шести чисел:
arr = np.linspace(1, 2, 6)
arr

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [51]:
#Обратиться к его элементу по индексу можно так же, как и к списку:
print(arr[2])

1.4


In [52]:
#Привычная запись для срезов работает и для одномерных массивов:
print(arr[2:4])

[1.4 1.6]


In [53]:
#Наконец, напечатать массив в обратном порядке можно с помощью привычной конструкции [::-1]:
print(arr[::-1])

[2.  1.8 1.6 1.4 1.2 1. ]


In [54]:
#С многомерными массивами работать немного интереснее. Создадим двумерный массив из одномерного:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
#Можно воспользоваться привычной записью нескольких индексов в нескольких квадратных скобках:
nd_array[1][2]
#Мы получили число из второй строки и третьего столбца массива.

np.float64(3.0)

In [56]:
#Мы бы так и делали, если бы приходилось работать со списком из списков. Однако проводить индексацию по массиву в NumPy можно проще: 
# достаточно в одних и тех же квадратных скобках перечислить индексы через запятую. Вот так:
nd_array[1, 2]

np.float64(3.0)

In [57]:
#Также через запятую можно передавать срезы или даже их комбинации с индексами. Например, получим все элементы из колонки 3 для первых двух строк:
nd_array[:2, 2]

array([1., 3.])

In [58]:
#Можно применять срезы сразу и к строкам, и к столбцам:
nd_array[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [59]:
#Чтобы получить все значения из какой-то оси, можно оставить на её месте двоеточие. Например, из всех строк получим срез с третьего по четвёртый столбцы:
nd_array[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [60]:
#Чтобы получить самую последнюю ось (в данном случае все столбцы), двоеточие писать необязательно. Строки будут получены целиком по умолчанию:
nd_array[:2]

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5]])

In [61]:
#Сортировка одномерных массивов
#Способ 1. Функция np.sort(<массив>) возвращает новый отсортированный массив:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
arr_new


array([ 3,  4, 12, 12, 15, 23, 23, 45])

In [62]:
#Способ 2. Функция <массив>.sort() сортирует исходный массив и возвращает None:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
# None
print(arr)

None
[ 3  4 12 12 15 23 23 45]


In [63]:
#Работа с пропущенными данными
data = np.array([4, 9, -4, 3])
#Воспользуемся встроенной в NumPy функцией sqrt, чтобы посчитать квадратные корни из элементов.
roots = np.sqrt(data)
roots

C:\Users\Denlex\AppData\Local\Temp\ipykernel_3020\302026354.py:4: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [64]:
#nan. Он расшифровывается как Not a number (не число). Этот объект аналогичен встроенному типу None, но имеет несколько отличий:
#1  None является отдельным объектом типа NoneType. np.nan — это отдельный представитель класса float:
#2  None могут быть равны друг другу, а np.nan — нет
print(None == None)
# True
print(np.nan == np.nan)
# False

True
False


In [65]:
sum(roots)

np.float64(nan)

In [66]:
np.isnan(roots)

array([False, False,  True, False])

In [67]:
roots[np.isnan(roots)]


array([nan])

In [ ]:
#Этим элементам можно присвоить новые значения, например 0:
roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [69]:
#После этого, если пропущенных значений больше нет, можем подсчитать сумму элементов массива:
sum(roots)
#Ранее проблема при подсчёте суммы элементов в массиве roots возникала из-за того, что отсутствовало значение для квадратного корня из -4 — вместо него было указано np.nan. 
# Сумма элементов массива, содержащего nan, также является nan. Поэтому приходится заменить nan, например, на 0, чтобы подсчитать сумму элементов массива.

np.float64(6.732050807568877)